### ISSUE TITLE
Not working as intended

### ISSUE THREAD

**Issue by RedDrumJay** [s3rgiosan/littlefoot#5]
Fresh out of the box it isn't working as expected for me. 

Also, is there a way to make it backward compatible with bigfoot and work with the footnote tags?

![image](https://github.com/s3rgiosan/littlefoot/assets/1888234/ee455723-6198-43aa-ad65-d6176a18023b)

**Comment by s3rgiosan** [comment]
Hey @RedDrumJay, 

> Fresh out of the box it isn't working as expected for me.

Can you describe what's not working?

> Also, is there a way to make it backward compatible with bigfoot and work with the footnote tags?

Unfortunately, no. This is only for the core Footnotes block.

**Comment by s3rgiosan** [comment]
This issue was closed because it’s been inactive for more than 30 days. If there’s still a need for this, please let us know — happy to revisit!
